export const DEFAULT_MENU = [
 {cat:'Suppen', no:'1', name:'Bohnensuppe', price:4.00},{cat:'Suppen', no:'2', name:'Gulaschsuppe', price:4.00},{cat:'Suppen', no:'3', name:'Hühnersuppe', price:4.00},{cat:'Suppen', no:'4', name:'Tomatensuppe', price:4.00},
 {cat:'Kalte Vorspeisen', no:'10', name:'Tzatziki', price:4.00},{cat:'Kalte Vorspeisen', no:'11', name:'Taramasalat', price:4.00},{cat:'Kalte Vorspeisen', no:'12', name:'Auberginensalat', price:4.00},{cat:'Kalte Vorspeisen', no:'13', name:'Oktopussalat', price:9.00},{cat:'Kalte Vorspeisen', no:'14', name:'Feta', price:6.00},{cat:'Kalte Vorspeisen', no:'15', name:'Oliven und Peperoni', price:4.50},{cat:'Kalte Vorspeisen', no:'16', name:'Chtipiti', price:4.10},{cat:'Kalte Vorspeisen', no:'17', name:'Skordalia', price:4.00},{cat:'Kalte Vorspeisen', no:'30', name:'Kalte Platte', price:13.00},
 {cat:'Warme Vorspeisen', no:'18', name:'Knoblauchbrot', price:2.50},{cat:'Warme Vorspeisen', no:'19', name:'Pita', price:2.50},{cat:'Warme Vorspeisen', no:'20', name:'Tiropitakia', price:6.00},{cat:'Warme Vorspeisen', no:'21', name:'Saganaki', price:6.50},{cat:'Warme Vorspeisen', no:'22', name:'Feta vom Backofen', price:6.50},{cat:'Warme Vorspeisen', no:'24', name:'Scampis im Backofen', price:12.00},{cat:'Warme Vorspeisen', no:'31', name:'Gegrillte Peperoni', price:4.50},{cat:'Warme Vorspeisen', no:'32', name:'Frittierte Muscheln mit Tzatziki und Brot', price:7.00},{cat:'Warme Vorspeisen', no:'33', name:'Surimi', price:8.00},
 {cat:'Salate', no:'35', name:'Beilagensalat', price:3.50},{cat:'Salate', no:'36', name:'Krautsalat', price:3.50},{cat:'Salate', no:'37', name:'Grüner Salat', price:3.50},{cat:'Salate', no:'38', name:'Bauernsalat', price:8.00},{cat:'Salate', no:'39', name:'Bauernsalat klein', price:6.00},{cat:'Salate', no:'41', name:'Griechischer Dorfsalat', price:9.00},{cat:'Salate', no:'42', name:'Chefsalat', price:10.00},{cat:'Salate', no:'43', name:'Scampi Salat', price:14.00},{cat:'Salate', no:'44', name:'Fitness Salat', price:12.00},{cat:'Salate', no:'61', name:'Meeresfrüchte Salat', price:12.50},{cat:'Salate', no:'501', name:'Gyrossalat', price:13.00},
 {cat:'Beilagen', no:'45', name:'Pommes Frites', price:3.50},{cat:'Beilagen', no:'46', name:'Reis', price:3.50},{cat:'Beilagen', no:'49', name:'Knoblauchkartoffel', price:4.00},
 {cat:'Grillgerichte', no:'65', name:'Gyros', price:13.00},{cat:'Grillgerichte', no:'66', name:'Gyros Pita', price:12.50},{cat:'Grillgerichte', no:'67', name:'Gyros - Souvlaki', price:12.50},{cat:'Grillgerichte', no:'68', name:'Gyros - Leber', price:12.50},{cat:'Grillgerichte', no:'69', name:'Souvlaki', price:12.00},{cat:'Grillgerichte', no:'70', name:'Leber', price:11.50},{cat:'Grillgerichte', no:'71', name:'Bifteki', price:13.00},{cat:'Grillgerichte', no:'72', name:'Lammkoteletts', price:18.00},{cat:'Grillgerichte', no:'73', name:'Puten-Spieß', price:13.00},{cat:'Grillgerichte', no:'75', name:'Schweinesteak', price:14.00},{cat:'Grillgerichte', no:'77', name:'Grill Teller', price:17.00},{cat:'Grillgerichte', no:'78', name:'Meteora-Teller', price:17.00},{cat:'Grillgerichte', no:'79', name:'Trikala-Teller', price:17.00},
 {cat:'Platten', no:'86', name:'Meteora-Platte für 2 Personen', price:38.00},{cat:'Platten', no:'88', name:'Spezial-Platte für 4 Personen', price:84.00},
 {cat:'Filet Gerichte', no:'91', name:'Schweinefilet', price:18.00},{cat:'Filet Gerichte', no:'92', name:'Schweinefilet gefüllt', price:20.00},{cat:'Filet Gerichte', no:'94', name:'Putenfilet mit Kräuterbutter', price:15.00},
 {cat:'Pfannen Gerichte', no:'100', name:'Gyros Pfanne', price:16.00},{cat:'Pfannen Gerichte', no:'103', name:'Leber Pfanne', price:16.00},{cat:'Pfannen Gerichte', no:'108', name:'Pfanne a la Chef für 2 Personen', price:38.00},
 {cat:'Aus dem Backofen', no:'109', name:'Soutzoukia mit Metaxasauce', price:15.50},{cat:'Aus dem Backofen', no:'110', name:'Gyros mit Metaxasauce', price:15.50},{cat:'Aus dem Backofen', no:'111', name:'Steak mit Metaxasauce', price:16.00},{cat:'Aus dem Backofen', no:'112', name:'Putenfleisch mit Metaxasauce', price:16.50},{cat:'Aus dem Backofen', no:'123', name:'Gyros Kritharakia mit Metaxasauce', price:16.50},{cat:'Aus dem Backofen', no:'124', name:'Gyros Spaghetti mit Metaxasauce', price:16.50},
 {cat:'Deutsche Gerichte', no:'125', name:'Schweineschnitzel paniert', price:12.50},{cat:'Deutsche Gerichte', no:'126', name:'Putenschnitzel paniert', price:13.50},{cat:'Deutsche Gerichte', no:'129', name:'Cordon bleu', price:14.00},{cat:'Deutsche Gerichte', no:'130', name:'Cordon bleu griechischer Art', price:14.50},{cat:'Deutsche Gerichte', no:'331', name:'Currywurst', price:9.00},{cat:'Deutsche Gerichte', no:'332', name:'Thomas Teller', price:10.50},
 {cat:'Für unsere kleinen Gäste', no:'131', name:'Souvlaki', price:10.00},{cat:'Für unsere kleinen Gäste', no:'132', name:'Gyros', price:10.50},{cat:'Für unsere kleinen Gäste', no:'133', name:'Schweineschnitzel Wiener Art', price:9.00},{cat:'Für unsere kleinen Gäste', no:'134', name:'Kalamaris', price:11.00},{cat:'Für unsere kleinen Gäste', no:'135', name:'Seezungenfilet', price:11.50},{cat:'Für unsere kleinen Gäste', no:'136', name:'Kalamaris - Gyros', price:12.00},
 {cat:'Nudeln', no:'151', name:'Kritharakia', price:9.00},{cat:'Nudeln', no:'152', name:'Spaghetti Napoli', price:8.50},{cat:'Nudeln', no:'153', name:'Spaghetti Meteora', price:10.50}
];
